# Generated by Django 3.0.6 on 2020-08-07 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='item_name',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller_name',
        ),
    ]
